// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechNation.Data.Context;

namespace TechNation.Migrations
{
    [DbContext(typeof(Data.Context.LogAppContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechNation.Dominio.LogEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CacheStatus");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("HttpMethod");

                    b.Property<string>("Provider");

                    b.Property<int>("ResponseSize");

                    b.Property<int>("StatusCode");

                    b.Property<double>("TimeTaken");

                    b.Property<string>("UriPath");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
